language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - travis_retry composer install --no-interaction --prefer-dist

script: make test
